### ISSUE TITLE
Lab1

### ISSUE THREAD

**Issue by AlekseiMaslakov** [aleksandraprohorova/LabsJava1sem#1]
Здравствуйте

a) Ok
b) Ok
c) Стоит пользователю всё же предоставлять список команд, которыми он может пользоваться, учитывая что они ещё и  регистрозависимые :)
Почему данная последовательность не работает? 
![image](https://user-images.githubusercontent.com/14160551/65877881-62478f80-e395-11e9-8205-566a7f03308b.png)

Общее замечание - структурируйте свои файлы, не надо всё ссыпать в один пакет.

**Comment by aleksandraprohorova** [comment]
@AlekseiMaslakov исправлено

**Comment by AlekseiMaslakov** [comment]
Lab1.c - Ok
