### ISSUE TITLE
Лабораторные 2 и 3

### ISSUE THREAD

**Issue by aleksandraprohorova** [aleksandraprohorova/LabsJava1sem#2]
@AlekseiMaslakov

**Comment by AlekseiMaslakov** [comment]
Здравствуйте
Lab2: файл есть, но не читается
![image](https://user-images.githubusercontent.com/14160551/68466385-5ae19480-0225-11ea-8a13-1c2e7cfc60df.png)
Lab3: есть вопросы к поведению toString(): зачем отменять операцию, которая не изменяет строку?
![image](https://user-images.githubusercontent.com/14160551/68466819-34702900-0226-11ea-9316-fa531e4bc718.png)
![image](https://user-images.githubusercontent.com/14160551/68466840-3f2abe00-0226-11ea-9da0-cf1e701988db.png)

**Comment by aleksandraprohorova** [comment]
@AlekseiMaslakov 
- В лабораторной 2 перед коммитом случайно убрала один символ в названии входного файла. Исправила, теперь работает
-  В лабораторной 3 исправила методы у CustomStringBuilder так, чтобы действия, не изменяющие строку не помещались в стек

**Comment by AlekseiMaslakov** [comment]
На самом деле, проблема не только в названии файла. Т.к. вы пользуетесь относительными путями, то путь к файлу будет считаться относительно корня проекта и будет выглядеть так: "lab2\\input.txt" из-за того, что все 3 лабы помещены в один проект/репозиторий на гите.
Это можно не исправлять, но учтите смещение путей в других работах.
